### ISSUE TITLE
No longer works after updating from 2023.10.5 to 2023.11.0b0

### ISSUE THREAD

**Issue by TonyOneZero** [bernikr/lovelace-notify-card#19]
No longer works after updating from 2023.10.5 to 2023.11.0b0. As you can see in the picture, the text line for entering the text is missing.

<img width="723" alt="image" src="https://github.com/bernikr/lovelace-notify-card/assets/15279954/75ec63e1-d22a-465c-a663-4e84a5977a5f">

**Comment by bernikr** [comment]
So, unfortunatly I dont have the time to fix this for a few weeks. But from what I found out it seems that the polymer `paper-input` textfield was deprecated and replaced by `ha-textfield`. Unfortunatly I don't know if it is a drop in replacement, especially with regard to the send button, so this card will stay broken until I have more time to commit to this or someone else submits a tested pull request.

**Comment by LookedPath** [comment]
@bernikr I've just submitted a pull request, the best I could do without tinkering too much is to have the button show on the outside of the text input but everything seems to be working fine.

![image](https://github.com/bernikr/lovelace-notify-card/assets/2457111/3669a8bc-6623-4d60-9c29-5a04db1b99b5)

**Comment by cataseven** [comment]
> @bernikr I've just submitted a pull request, the best I could do without tinkering too much is to have the button show on the outside of the text input but everything seems to be working fine.
> 
> ![image](https://user-images.githubusercontent.com/2457111/280114136-3669a8bc-6623-4d60-9c29-5a04db1b99b5.png)

How can I use card-mod for this version? ha-card no longer work

**Comment by TonyOneZero** [comment]
@cataseven Error already fixed. You just have to reinstall the card. Unfortunately, no update is displayed in HACS, so this must be done manually by reinstalling the card

**Comment by cataseven** [comment]
@TonyOneZero 

On previous version I was using below code to hide border of text field. So text field and background looks like "merged". No longer work

card_mod:
  style: |
    ha-card {
      box-shadow: 0px 0px !important;
      color: #2cd669;
      border-style: none               
    }  


![image](https://github.com/bernikr/lovelace-notify-card/assets/52464808/9593c21e-f115-4d05-9f30-ca96d70066ce)

**Comment by cataseven** [comment]
card_mod:
  style: |
    ha-card: {
      background-color: rgb(65 43 43 / 5%);     
      border-bottom-width: 0px !important;
    }  


ok. Aboce code solved the color issue. Now I am trying to remove bottom line. If I changed below code on chrome console to 0px; it works. How can I add it to my card-mod code? (Sorry I am not a developer)

    .mdc-line-ripple::before {
    border-bottom-width: 0px;
