### ISSUE TITLE
No card in Lovelace

### ISSUE THREAD

**Issue by Friedi1970** [bernikr/lovelace-notify-card#7]
I installed via HACS and did a reboot but the custom card is not available. Even when I create a manual card it is not possible because the card is not available.

I also tried to install manually but I don't know where to add the resource:
```
resources:
  - url: /local/notify-card.js
    type: module
```
If I add this code to config.yaml I get an error.

**Comment by bernikr** [comment]
There is no need for a reboot but you have to reload the frontend after installing. HACS should provide the option for this. If not you can use your browsers developer tools to "Empty Cache and Hard Reload".

If you install manually you can find the resource configuration in the UI under Configuration -> Lovelace Dashboards -> Resources. Or click this link: https://my.home-assistant.io/redirect/lovelace_resources/

If you installed it through HACS the resources page should show that as well.

I hope that helps.

**Comment by Friedi1970** [comment]
Yes, I chose empty cash. And because it didn’t work I did a reboot what didn’t work either.

**Comment by Friedi1970** [comment]
Btw. The link is already in the resources but the card isn’t available.

**Comment by bernikr** [comment]
Can you post the configuration you tried with a manual card?

**Comment by Friedi1970** [comment]
Well, I thought there must be a notify card. When I tried with manual card it works.

Thanks for the hint!
